name: My first workflow

on: 
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello world
        run: echo 'Hello world'
      
      
      
